# Generated by Django 4.1 on 2023-01-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(default='./../user-icon.png', upload_to='clients/'),
        ),
    ]
